---

- name: Remove Grafana 
  hosts: hosts
  become: yes
  
  tasks:
  - name: remove apt key
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      id: 4E40DDF6D76E284A4A6780E48C8C34C524098CB6
      state: absent
   
  - name: Remove Grafana repo from sources.list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      filename: grafana
      state: absent

  - name: Ensure Grafana service is stopped and disabled
    ansible.builtin.service:
      name: grafana-server
      state: stopped
      enabled: no
      
      
  - name: Remove apt cache and uninstall Grafana
    ansible.builtin.apt:
      name: grafana
      state: absent
      
  
    