---

- name: Install Jenkins
  hosts: localhost
  become: yes

  tasks: 
  - name: Download apt key for Jenkins
    ansible.builtin.apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present
  
  - name: Add Jenkins repo to sources.list 
    ansible.builtin.apt_repository:
      repo: deb http://pkg.jenkins.io/debian-stable binary/
      filename: jenkins
      state: present
  
  - name: update apt cache and install Jenkins
    apt:
      name: jenkins
      update_cache: yes
  
  - name: Ensure Jenkins service is started and enabled
    ansible.builtin.service:
      name: jenkins
      state: started
      enabled: yes
   